### ISSUE TITLE
Decoding problems

### ISSUE THREAD

**Issue by oren4323** [lemire/SIMDCompressionAndIntersection#18]
When trying to decode values after encoding them I receive error.
[valuesBug.txt](https://github.com/lemire/SIMDCompressionAndIntersection/files/713915/valuesBug.txt)
I'm attaching a file with 1931 numbers, the compression seems to be working fine, decoding's failing.

I've used:
	CompositeCodec<BinaryPacking<BasicBlockPacker>,
		VariableByte<true>> codec = CompositeCodec<BinaryPacking<BasicBlockPacker>,
		VariableByte<true>>();

**Comment by lemire** [comment]
Added your array with 1931 numbers to our unit tests, please see the following commit...

https://github.com/lemire/SIMDCompressionAndIntersection/commit/64b6a0d3b7c400c7d25377444f05ca7fdb04cb9a

No issue found.

Please sync the code and check the unit tests.

If you think there is still a problem, please provide a full unit test that we can verify.

**Comment by oren4323** [comment]
Yes, you are correct, I misused your code.
Thank you for the fast response.
