### ISSUE TITLE
Conflicting Namespaces

### ISSUE THREAD

**Issue by aconz2** [lemire/SIMDCompressionAndIntersection#2]
`SIMDCompressionAndIntersection` shares many classes and header file names with `FastPFor`. When using them together, there are issues since this library doesn't enclose anything in a namespace.
I'm proposing renaming all `#ifndef NAME_H_` to `#ifndef SIMDCompressionAndIntersection_NAME_H_` and enclosing all relevant pieces in a namespace, maybe called `SIMDCompressionLib`?
If these sound like reasonable names and changes, I will go ahead and do so.

**Comment by lemire** [comment]
Yes, this does sound reasonable. A PR would be appreciated.

**Comment by aconz2** [comment]
Submitted: #3

**Comment by lemire** [comment]
@aconz2 

Your PR is excellent. I have added your name to the README and CHANGELOG.

I am closing this issue, reopen if you disagree.

**Comment by aconz2** [comment]
Cheers. Thanks for making this code available in the first place.
