### ISSUE TITLE
scalar vs nate_scalar

### ISSUE THREAD

**Issue by travisdowns** [lemire/SIMDCompressionAndIntersection#23]
The intersection header has this method:

```
/*
 * Given two arrays, this writes the intersection to out. Returns the
 * cardinality of the intersection.
 *
 * This is a well-written, but otherwise unsophisticated function.
 * Written by N. Kurz.
 */
size_t nate_scalar(const uint32_t *set1, const size_t length1,
                   const uint32_t *set2, const size_t length2, uint32_t *out);
```

However, it is not implemented anywhere. There is an implemented method called `scalar` which doesn't appear in the header. Is one of them named from?

@nkurz @lemire

**Comment by lemire** [comment]
It is just the 'scalar' function. I must have renamed it (to remove the unnecessary prefix 'nate_scalar') and never gone back to the header to change the name there. I changed its name to 'scalar' in the latest commit.

Note: we used to have several such scalar functions but Nate's version was all around faster... so everything else was eventually dropped.

**Comment by lemire** [comment]
Closing.
