### ISSUE TITLE
fastpfor codec has a bug

### ISSUE THREAD

**Issue by tanglianggithub** [lemire/SIMDCompressionAndIntersection#24]
```
./example
You are using 2.09 bits per integer.
terminate called after throwing an instance of 'std::runtime_error'
  what():  bug!
Aborted (core dumped)
```

![image](https://user-images.githubusercontent.com/3445470/86900417-e78a7c80-c13d-11ea-9fd6-11cbc1e3bb4f.png)

**Comment by lemire** [comment]
Thanks for your interest.

There is no bug in this codec. The example does work and the recovered data is identical to the input (you can check by printing it out if you'd like).

In this library, codecs use differential coding. The codecs that are unable to compute the differential coding as part of the encoding routine must do it as a separate pass... So the input data is modified and you need to adapt the example accordingly... 


Please see our article to know more...

Daniel Lemire, Leonid Boytsov, Nathan Kurz, SIMD Compression and the Intersection of Sorted Integers, Software Practice & Experience 46 (6), 2016 http://arxiv.org/abs/1401.6399


I modified the example on GitHub to include an explanation.
